(function(root){'use strict';
const API='https://api.github.com',TEST_REPO='chance-hang/myBlog-test',CONTENT_PATH='content.json',COLLECTIONS={article:'articles',note:'notes',topic:'topics'},CATEGORIES=new Set(['project','ai','life']),RULES={article:{required:['id','date','type','category','reading','title','summary','body'],optional:['cover','imageRefs']},note:{required:['id','date','label','category','text'],optional:['imageRefs']},topic:{required:['id','date','title','status','text'],optional:['category','imageRefs']}},state={token:'',document:null,blobSha:'',editingId:null,editingItem:null,activeKind:'article',history:[]};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeUrl(v){return /^(?:javascript|vbscript|data):/i.test(String(v||'').trim())?'#':v}
function enc(v){return btoa(unescape(encodeURIComponent(v)))}function dec(v){return decodeURIComponent(escape(atob(String(v).replace(/\n/g,''))))}
function stable(kind,id){return new RegExp('^'+kind+'_[0-7][0-9A-HJKMNP-TV-Z]{25}$').test(id||'')}
function stableJson(v){return JSON.stringify(v,null,2)+'\n'}function clone(v){return JSON.parse(JSON.stringify(v))}
function validateItem(kind,item){if(!item||typeof item!=='object'||Array.isArray(item))throw Error(kind+' 条目必须是对象');const r=RULES[kind];if(!r)throw Error('未知内容类型：'+kind);const allowed=new Set([...r.required,...r.optional]);Object.keys(item).forEach(k=>{if(!allowed.has(k))throw Error(kind+' 含未知字段：'+k)});r.required.forEach(k=>{if(typeof item[k]!=='string'||!item[k])throw Error(kind+' 的 '+k+' 为必填非空文本')});if(!stable(kind,item.id))throw Error(kind+' ID 必须是 '+kind+'_<ULID>');if(Object.hasOwn(item,'cover')&&(typeof item.cover!=='string'||!item.cover))throw Error('cover 必须是非空文本');if(Object.hasOwn(item,'category')&&(typeof item.category!=='string'||!item.category))throw Error('category 必须是非空文本');if(Object.hasOwn(item,'imageRefs')&&!Array.isArray(item.imageRefs))throw Error('imageRefs 必须是数组')}
function validateContentDocument(doc){if(!doc||typeof doc!=='object'||Array.isArray(doc))throw Error('content.json 顶层必须是对象');const top=new Set(['schemaVersion','articles','notes','topics']);Object.keys(doc).forEach(k=>{if(!top.has(k))throw Error('content.json 含未知顶层字段：'+k)});if(doc.schemaVersion!==1)throw Error('仅支持 schemaVersion: 1');const seen=new Set;Object.entries(COLLECTIONS).forEach(([kind,list])=>{if(!Array.isArray(doc[list]))throw Error(list+' 必须是数组');doc[list].forEach(item=>{validateItem(kind,item);if(seen.has(item.id))throw Error('重复 ID：'+item.id);seen.add(item.id)})});return doc}
function parseContentJson(t){return validateContentDocument(JSON.parse(t))}
function preserveOptional(kind,existing){const out={};if(!existing)return out;RULES[kind].optional.forEach(k=>{if(Object.hasOwn(existing,k))out[k]=clone(existing[k])});return out}
function serializeItem(kind,values,existing){return Object.assign(preserveOptional(kind,existing),values)}
function upsertItem(doc,kind,item,editingId){validateItem(kind,item);const next=clone(doc),list=COLLECTIONS[kind],all=Object.values(COLLECTIONS).flatMap(k=>next[k]);if(editingId){if(item.id!==editingId)throw Error('编辑已有内容不得改变稳定 ID');const i=next[list].findIndex(x=>x.id===editingId);if(i<0)throw Error('待编辑条目不存在于当前 Test 基线，请重新读取');next[list][i]=clone(item)}else{if(all.some(x=>x.id===item.id))throw Error('重复 ID：'+item.id);next[list].push(clone(item))}return validateContentDocument(next)}
function ulid(now=Date.now(),cryptoApi=root.crypto){if(!cryptoApi||typeof cryptoApi.getRandomValues!=='function')throw Error('浏览器不支持安全随机数，无法生成 ULID');const a='0123456789ABCDEFGHJKMNPQRSTVWXYZ';let t=now,out='';for(let i=0;i<10;i++){out=a[t%32]+out;t=Math.floor(t/32)}const b=new Uint8Array(16);cryptoApi.getRandomValues(b);let bits=0,v=0;b.forEach(x=>{v=(v<<8)|x;bits+=8;while(bits>=5&&out.length<26){bits-=5;out+=a[(v>>>bits)&31]}});return out.slice(0,26)}
function headers(token,extra){return Object.assign({Authorization:'Bearer '+token,Accept:'application/vnd.github+json'},extra||{})}
async function getContent(token){const r=await fetch(API+'/repos/'+TEST_REPO+'/contents/'+CONTENT_PATH,{headers:headers(token)}),j=await r.json().catch(()=>({}));if(!r.ok||!j.sha||!j.content)throw Error('读取 Test content.json 失败：'+r.status+' '+(j.message||''));return {document:parseContentJson(dec(j.content)),sha:j.sha}}
async function putContent(content,token,sha){const r=await fetch(API+'/repos/'+TEST_REPO+'/contents/'+CONTENT_PATH,{method:'PUT',headers:headers(token,{'Content-Type':'application/json'}),body:JSON.stringify({message:'admin: update Test content.json',content:enc(content),sha})}),j=await r.json().catch(()=>({}));if(r.status===409||r.status===422){const e=Error('Test 基线已变化，已停止写入。请重新读取 content.json 后再处理。');e.code='BASELINE_CONFLICT';throw e}if(!r.ok)throw Error('写入 content.json 失败：'+r.status+' '+(j.message||''));return j}
function markdown(s){let h=esc(s||'');h=h.replace(/```([\s\S]*?)```/g,(m,c)=>'<pre><code>'+c.replace(/^\n/,'')+'</code></pre>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/!\[([^\]]*)\]\(([^)\s]+)\)/g,(m,a,u)=>'<img src="'+safeUrl(u)+'" alt="'+a+'">').replace(/\[([^\]]+)\]\(([^)\s]+)\)/g,(m,t,u)=>'<a href="'+safeUrl(u)+'" target="_blank" rel="noopener">'+t+'</a>').replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/^[-*] (.*)$/gm,'<li>$1</li>');h=h.replace(/(?:<li>.*<\/li>\n?)+/g,m=>'<ul>'+m+'</ul>');return h.split(/\n{2,}/).map(b=>/^<(h[1-3]|pre|ul)/.test(b.trim())?b:'<p>'+b.replace(/\n/g,'<br>')+'</p>').join('\n')}
function el(id){return document.getElementById(id)}
function message(t,k){const node=el('msg');if(!node)return;node.textContent=t;node.className=k||'';if(t)setTimeout(()=>{if(node.textContent===t){node.textContent='';node.className=''}},4500)}
function labelForKind(k){return k==='article'?'文章':k==='note'?'短记':'专题'}
function titleFor(kind,item){return kind==='article'?item.title:kind==='note'?item.label:item.title}
function summaryFor(kind,item){return kind==='article'?item.summary:(item.text||'').replace(/\s+/g,' ').slice(0,80)}
function bodyFor(kind,item){return kind==='article'?item.body:item.text}
function setHeaderForKind(kind){state.activeKind=kind;const title=labelForKind(kind);el('list-heading').textContent=title;el('new-button').textContent='＋ 新建'+title;document.querySelectorAll('[data-kind-filter]').forEach(b=>b.classList.toggle('active',b.dataset.kindFilter===kind));if(el('type-filter'))el('type-filter').value=kind;renderList()}
function kindFields(){const k=el('content-kind').value;document.querySelectorAll('.article-only').forEach(x=>x.classList.toggle('hidden',k!=='article'));document.querySelectorAll('.note-only').forEach(x=>x.classList.toggle('hidden',k!=='note'));document.querySelectorAll('.topic-only').forEach(x=>x.classList.toggle('hidden',k!=='topic'));document.querySelectorAll('.category-field').forEach(x=>x.classList.toggle('hidden',k==='topic'));el('kind-pill').textContent=k;el('kind-pill').className='kind-pill '+k}
function syncDisplayTitle(){const k=el('content-kind').value;let v='';if(k==='article')v=el('content-title').value;if(k==='note')v=el('note-label').value;if(k==='topic')v=el('topic-title').value;el('editor-display-title').value=v||('新建'+labelForKind(k))}
function preview(){const text=el('content-body').value,html=markdown(text);el('preview').innerHTML=html;el('preview-full').innerHTML=html;el('word-count').textContent='字数：'+text.replace(/\s/g,'').length}
function rememberHistory(){const ta=el('content-body');if(!ta)return;state.history.push({value:ta.value,start:ta.selectionStart,end:ta.selectionEnd});if(state.history.length>50)state.history.shift()}
function reset(){state.editingId=null;state.editingItem=null;state.history=[];const k=state.activeKind||'article';el('content-kind').disabled=false;el('content-kind').value=k;el('content-id').value='';el('content-date').value=new Date().toISOString().slice(0,10);el('content-category').value='project';el('article-type').value='article';['article-reading','content-title','article-summary','note-label','topic-title','topic-status','content-body'].forEach(id=>el(id).value='');el('edit-mode').textContent='新建条目会生成不可变稳定 ID。';kindFields();syncDisplayTitle();preview();activateView('meta');renderList()}
function form(){const k=el('content-kind').value,id=state.editingId||k+'_'+ulid(),d=el('content-date').value,b=el('content-body').value;if(k==='article')return serializeItem(k,{id,date:d,type:el('article-type').value,category:el('content-category').value,reading:el('article-reading').value,title:el('content-title').value,summary:el('article-summary').value,body:b},state.editingItem);if(k==='note')return serializeItem(k,{id,date:d,label:el('note-label').value,category:el('content-category').value,text:b},state.editingItem);return serializeItem(k,{id,date:d,title:el('topic-title').value,status:el('topic-status').value,text:b},state.editingItem)}
function rows(){if(!state.document)return[];const q=(el('content-search').value||'').trim().toLowerCase(),filter=el('type-filter').value||state.activeKind,status=el('status-filter').value,sort=el('sort-filter').value;let out=Object.entries(COLLECTIONS).flatMap(([k,l])=>state.document[l].map(i=>({k,i})));if(filter!=='all')out=out.filter(x=>x.k===filter);if(status==='editing')out=out.filter(x=>x.i.id===state.editingId);if(q)out=out.filter(({k,i})=>[i.id,i.date,titleFor(k,i),summaryFor(k,i)].join(' ').toLowerCase().includes(q));out.sort((a,b)=>String(a.i.date).localeCompare(String(b.i.date))*(sort==='asc'?1:-1));return out}
function libraryRows(doc,query='',kind='all',category='all'){const q=String(query).toLowerCase();return Object.entries(COLLECTIONS).flatMap(([k,list])=>(doc&&doc[list]||[]).map(i=>({k,i}))).filter(({k,i})=>(kind==='all'||k===kind)&&(category==='all'||i.category===category)&&[i.title,i.label,i.summary,i.body,i.text,i.id].some(v=>String(v||'').toLowerCase().includes(q))).sort((a,b)=>String(b.i.date||'').localeCompare(String(a.i.date||'')))}
function switchMode(mode,nodes){const visible={test:mode==='test',prod:mode==='prod'};nodes.test.hidden=!visible.test;nodes.prod.hidden=!visible.prod;return visible}
function editorVisibility(view){return {edit:view==='edit',preview:view==='preview',meta:view==='meta'}}
function layoutContract(w,h){return {columns:w>=1366&&h>=768?3:w>=900?2:1,overlap:false}}
function renderList(){const box=el('post-list'),items=rows();box.innerHTML='';el('item-count').textContent=items.length;if(!state.document){box.innerHTML='<div class="empty-state">连接 Test 后显示内容。</div>';return}if(!items.length){box.innerHTML='<div class="empty-state">当前筛选条件下暂无内容。</div>';return}items.forEach(({k,i})=>{const row=document.createElement('div');row.className='list-item'+(state.editingId===i.id?' active':'');row.tabIndex=0;row.innerHTML='<div class="list-title-row"><div class="list-title">'+esc(titleFor(k,i)||'(无标题)')+'</div><button type="button" class="list-more" aria-label="条目更多操作">•••</button></div><div class="list-meta"><span>'+esc(i.date)+'</span><span class="kind-tag '+k+'">'+labelForKind(k)+'</span></div><div class="list-summary">'+esc(summaryFor(k,i))+'</div>';row.onclick=e=>{if(e.target.closest('.list-more')){e.stopPropagation();edit(k,i.id);message('当前阶段仅支持编辑；删除与直接 Prod 发布均未开放。');return}edit(k,i.id)};row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();edit(k,i.id)}};box.appendChild(row)})}
function edit(k,id){const i=state.document&&state.document[COLLECTIONS[k]].find(x=>x.id===id);if(!i)return;state.activeKind=k;state.editingId=id;state.editingItem=clone(i);state.history=[];el('content-kind').value=k;el('content-kind').disabled=true;el('content-id').value=id;el('content-date').value=i.date;el('content-category').value=i.category||'';if(k==='article'){el('article-type').value=i.type;el('article-reading').value=i.reading;el('content-title').value=i.title;el('article-summary').value=i.summary;el('content-body').value=i.body}if(k==='note'){el('note-label').value=i.label;el('content-body').value=i.text}if(k==='topic'){el('topic-title').value=i.title;el('topic-status').value=i.status;el('content-body').value=i.text}el('edit-mode').textContent='ID：'+id+'　日期：'+i.date+'　稳定 ID 与内容类型已锁定';kindFields();syncDisplayTitle();preview();setHeaderForKind(k);activateView('edit');renderList()}
function activateView(view){document.querySelectorAll('.editor-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.view-panel').forEach(p=>p.classList.remove('active'));const panel=el(view+'-view');if(panel)panel.classList.add('active')}
function wrapSelection(before,after,placeholder){const ta=el('content-body');rememberHistory();const start=ta.selectionStart,end=ta.selectionEnd,selected=ta.value.slice(start,end)||placeholder||'';ta.setRangeText(before+selected+after,start,end,'end');preview();ta.focus()}
function prefixLines(prefix){const ta=el('content-body');rememberHistory();const start=ta.selectionStart,end=ta.selectionEnd;const lineStart=ta.value.lastIndexOf('\n',start-1)+1;let block=ta.value.slice(lineStart,end||start);if(!block)block='文本';const out=block.split('\n').map((line,i)=>typeof prefix==='function'?prefix(line,i):prefix+line).join('\n');ta.setRangeText(out,lineStart,end||start,'end');preview();ta.focus()}
function toolbarCommand(command){const ta=el('content-body');if(!ta)return;if(command==='undo'){const prev=state.history.pop();if(prev){ta.value=prev.value;ta.setSelectionRange(prev.start,prev.end);preview();ta.focus()}else message('没有可撤销的编辑。');return}if(command==='bold')return wrapSelection('**','**','加粗文字');if(command==='italic')return wrapSelection('*','*','斜体文字');if(command==='h1')return prefixLines('# ');if(command==='h2')return prefixLines('## ');if(command==='h3')return prefixLines('### ');if(command==='ul')return prefixLines('- ');if(command==='ol')return prefixLines((line,i)=>(i+1)+'. '+line);if(command==='code')return wrapSelection('`','`','代码');if(command==='link'){const text=ta.value.slice(ta.selectionStart,ta.selectionEnd)||'链接文字',url=root.prompt('请输入链接 URL：','https://');if(url)wrapSelection('[',']('+url+')',text);return}if(command==='image'){message('图片写入当前阶段已禁用：无法保证图片与 content.json 原子提交。','err')}}
async function load(){state.token=el('token-input').value.trim();if(!state.token)return message('请输入仅限 myBlog-test 的 Fine-grained PAT。','err');try{message('正在读取并校验 Test content.json…');const r=await getContent(state.token);state.document=r.document;state.blobSha=r.sha;el('baseline-sha').textContent=r.sha;el('publish-button').disabled=false;el('refresh-button').disabled=false;reset();renderList();message('Test content.json 已通过 schemaVersion 1 校验。','ok')}catch(e){message(e.message,'err')}}
async function publish(){if(!state.document)return message('请先读取 Test content.json。','err');try{const k=el('content-kind').value,i=form(),next=upsertItem(state.document,k,i,state.editingId);message('校验通过，正在以读取到的 blob SHA 写入 Test…');const r=await putContent(stableJson(next),state.token,state.blobSha),commit=r.commit&&r.commit.sha,sha=r.content&&r.content.sha;if(!commit||!sha)throw Error('GitHub 未返回完整写入回执，无法确认发布完成');state.document=next;state.blobSha=sha;el('baseline-sha').textContent=sha;el('receipt').innerHTML='<strong>Test 写入回执</strong><br>commit SHA: '+esc(commit)+'<br>content blob SHA: '+esc(sha)+'<br>item ID: '+esc(i.id);el('receipt').classList.remove('hidden');message('已写入 Test content.json。请使用回执 SHA 在测试站核对。','ok');edit(k,i.id)}catch(e){if(e.code==='BASELINE_CONFLICT')el('publish-button').disabled=true;message(e.message,'err')}}
function showSafeNotice(title,text){activateView('meta');message(title+'：'+text)}
function setEnvironment(mode){const prod=mode==='prod';el('app-shell').hidden=prod;el('prod-mode').hidden=!prod;el('test-env-button').classList.toggle('active',!prod);el('prod-env-button').classList.toggle('active',prod);el('test-env-button').setAttribute('aria-pressed',String(!prod));el('prod-env-button').setAttribute('aria-pressed',String(prod));if(prod)message('Prod 为受控发布流程：请先完成 Test 内容读取。')}
const api={COLLECTIONS,RULES,parseContentJson,validateContentDocument,validateItem,serializeItem,upsertItem,ulid,stable,stableJson,state,setEnvironment,libraryRows,switchMode,editorVisibility,layoutContract};
if(typeof module!=='undefined'&&module.exports)module.exports=api;
root.MyBlogAdmin=api;
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',()=>{
  el('connect-button').onclick=load;el('refresh-button').onclick=load;el('publish-button').onclick=publish;el('new-button').onclick=reset;
  el('content-kind').onchange=()=>{state.activeKind=el('content-kind').value;kindFields();syncDisplayTitle();setHeaderForKind(state.activeKind)};
  el('content-body').addEventListener('beforeinput',()=>rememberHistory());el('content-body').oninput=preview;
  ['content-title','note-label','topic-title'].forEach(id=>el(id).addEventListener('input',syncDisplayTitle));
  document.querySelectorAll('[data-kind-filter]').forEach(b=>b.onclick=()=>{setHeaderForKind(b.dataset.kindFilter);reset()});
  document.querySelectorAll('.editor-tab').forEach(b=>b.onclick=()=>activateView(b.dataset.view));
  document.querySelectorAll('.toolbar-button[data-command]').forEach(b=>b.onclick=()=>toolbarCommand(b.dataset.command));
  el('toolbar-help').onclick=()=>message('Markdown：# 标题、**加粗**、*斜体*、- 列表、[文字](URL)、`代码`。');
  el('content-search').oninput=renderList;el('type-filter').onchange=()=>{const v=el('type-filter').value;if(v!=='all')state.activeKind=v;renderList()};el('status-filter').onchange=renderList;el('sort-filter').onchange=renderList;
  el('settings-nav').onclick=()=>{el('access-card').open=true;el('token-input').focus();message('设置入口当前提供 Test 凭据连接；令牌不会写入浏览器存储。')};
  el('help-nav').onclick=()=>message('使用顺序：连接 Test → 选择/新建内容 → 编辑或元数据 → 提交到 Test。Prod 需单独安全发布流程。');
  el('publish-nav').onclick=()=>setEnvironment('prod');
  el('prod-env-button').onclick=()=>setEnvironment('prod');
  el('test-env-button').onclick=()=>setEnvironment('test');
  el('back-to-test').onclick=()=>setEnvironment('test');
  el('editor-more-button').onclick=()=>message('更多操作：当前仅开放编辑与提交 Test；删除和直接 Prod 发布均未开放。');
  el('user-menu-button').onclick=()=>message('当前用户：杭诚。此静态维护台没有独立账户会话。');
  reset();
})
})(typeof window!=='undefined'?window:globalThis);
