(function(root){'use strict';
const API='https://api.github.com',TEST='chance-hang/myBlog-test',PROD='chance-hang/myBlog-prod',CONTENT='content.json',UPLOAD=/^assets\/uploads\/[a-f0-9]{64}\.(?:png|jpe?g|gif|webp|svg)$/;
const collections={article:'articles',note:'notes',topic:'topics'};
const canonical=v=>JSON.stringify(sort(v));function sort(v){if(Array.isArray(v))return v.map(sort);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])]));return v}
const itemHash=async v=>{const c=requireCrypto();if(c)return c.createHash('sha256').update(canonical(v)).digest('hex');const b=await root.crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(v)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')};
function requireCrypto(){try{return typeof require==='function'?require('node:crypto'):null}catch{return null}}
function releaseId(now,ulid,hash){return new Date(now).toISOString().replace(/[-:.TZ]/g,'').slice(0,14)+'-'+ulid+'-'+hash.slice(0,8)}
function entries(doc){return Object.entries(collections).flatMap(([kind,key])=>(doc[key]||[]).map(value=>({kind,value})))}
function refs(item){const text=[item.body,item.text,item.cover,...(item.imageRefs||[])].filter(Boolean).join('\n');const found=[...text.matchAll(/!?\[[^\]]*\]\((assets\/uploads\/[^)\s]+)\)/g)].map(x=>x[1]);return [...new Set([...found,...(item.imageRefs||[]),...(item.cover?[item.cover]:[])])].filter(x=>x.startsWith('assets/uploads/'))}
function assertPlan(plan){if(!plan||plan.repo!==PROD||!/^\d{14}-[0-9A-HJKMNP-TV-Z]{26}-[a-f0-9]{8}$/.test(plan.releaseId))throw Error('非法 release plan');if(!Array.isArray(plan.selectedEntries)||!plan.selectedEntries.length)throw Error('必须选择内容');if(!/^[a-f0-9]{40}$/.test(plan.sourceTestCommitSha)||!/^[a-f0-9]{40}$/.test(plan.prodBaselineCommitSha)||!/^[a-f0-9]{40}$/.test(plan.prodContentBlobSha))throw Error('release plan 缺少 commit/blob 基线');plan.images.forEach(x=>{if(!UPLOAD.test(x.path)||!/^[a-f0-9]{64}$/.test(x.sha256))throw Error('图片路径或 hash 不符合白名单')});return plan}
async function buildPlan({source,prod,sourceSha,prodSha,prodBlobSha,selected,operator,testAcceptance,now=Date.now(),ulid}){const lookup=new Map(entries(source).map(({kind,value})=>[value.id,{kind,value}]));const target=new Map(entries(prod).map(({value})=>[value.id,value]));const selectedEntries=await Promise.all(selected.map(async id=>{const x=lookup.get(id);if(!x)throw Error('所选 ID 不在 Test 基线：'+id);return {kind:x.kind,id,sourceHash:await itemHash(x.value),targetBeforeHash:target.has(id)?await itemHash(target.get(id)):null}}));const images=[...new Set(selected.flatMap(id=>refs(lookup.get(id).value)))].sort().map(path=>{if(!UPLOAD.test(path))throw Error('图片必须使用 assets/uploads/ 下的 SHA-256 命名文件');return {path,sha256:path.match(/\/([a-f0-9]{64})\./)[1],sourceRef:path}});const draft={repo:PROD,sourceTestCommitSha:sourceSha,prodBaselineCommitSha:prodSha,prodContentBlobSha:prodBlobSha,selectedEntries,images,operator,testAcceptance,createdAtUtc:new Date(now).toISOString()};const planHash=await itemHash(draft);return Object.freeze({...draft,releaseId:releaseId(now,ulid,planHash),planHash})}
async function getJson(url,token){const h={Accept:'application/vnd.github+json'};if(token)h.Authorization='Bearer '+token;const r=await fetch(url,{headers:h}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error((j.message||'GitHub 请求失败')+' ('+r.status+')');return j}
async function readBaseline(repo,token){const head=await getJson(API+'/repos/'+repo+'/git/ref/heads/main',token);const file=await getJson(API+'/repos/'+repo+'/contents/'+CONTENT,token);const decode=s=>decodeURIComponent(escape(atob(s.replace(/\n/g,''))));return {commitSha:head.object.sha,blobSha:file.sha,document:JSON.parse(decode(file.content))}}
function mount(){const el=id=>document.getElementById(id),msg=t=>el('phase-c-msg').textContent=t;el('phase-c-read').onclick=async()=>{try{const token=el('token-input').value.trim();if(!root.MyBlogAdmin||!root.MyBlogAdmin.state)throw Error('请先读取 Test 内容');const source=root.MyBlogAdmin.state.document;if(!source)throw Error('请先读取 Test content.json');msg('正在读取公开 Prod 基线…');const prod=await readBaseline(PROD,'');root.PhaseC={source,prod,token};el('phase-c-prod-sha').textContent=prod.commitSha;el('phase-c-selection').innerHTML=entries(source).map(x=>'<label><input type="checkbox" name="phase-c-entry" value="'+x.value.id+'"> '+x.kind+' / '+x.value.id+'</label>').join('<br>');el('phase-c-plan').disabled=false;msg('Prod 基线已读取。请选择要提升的稳定 ID。')}catch(e){msg(e.message)}};el('phase-c-plan').onclick=async()=>{try{const p=root.PhaseC;if(!p)throw Error('请先读取 Prod 基线');const selected=[...document.querySelectorAll('input[name="phase-c-entry"]:checked')].map(x=>x.value);const acceptance={url:el('phase-c-test-url').value.trim(),commitSha:el('phase-c-test-sha').value.trim(),confirmedAtUtc:el('phase-c-confirmed').checked?new Date().toISOString():''};if(!acceptance.url||!acceptance.commitSha||!acceptance.confirmedAtUtc)throw Error('必须填写 Test URL、已验收 SHA 并确认已人工验收');const plan=await buildPlan({source:p.source,prod:p.prod.document,sourceSha:el('phase-c-test-sha').value.trim(),prodSha:p.prod.commitSha,prodBlobSha:p.prod.blobSha,selected,operator:el('phase-c-operator').value.trim(),testAcceptance:acceptance,ulid:root.MyBlogAdmin.ulid()});el('phase-c-output').value=JSON.stringify(plan,null,2);el('phase-c-dispatch').disabled=false;msg('不可变 release plan 已生成；请人工复核后提交 Actions。')}catch(e){msg(e.message)}};el('phase-c-dispatch').onclick=async()=>{try{const token=el('phase-c-dispatch-token').value.trim(),plan=el('phase-c-output').value;if(!token||!plan)throw Error('需要操作员 token 与已生成 plan');await fetch(API+'/repos/chance-hang/myBlog-admin/actions/workflows/publish-prod-content.yml/dispatches',{method:'POST',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify({ref:'main',inputs:{release_plan:plan}})}).then(r=>{if(!r.ok)throw Error('提交受控发布会话失败：'+r.status)});msg('已提交受控发布会话；实际写入仍需 GitHub Environment approval。')}catch(e){msg(e.message)}}};
const api={buildPlan,assertPlan,refs,itemHash,releaseId,readBaseline,PROD,TEST};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.AdminPhaseC=api;if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',mount)})(typeof window!=='undefined'?window:globalThis);
