'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const source = fs.readFileSync(require('node:path').join(__dirname, '..', 'admin.js'), 'utf8');
assert.match(source, /function serializeItem/);
assert.match(source, /function preserveOptional/);
assert.match(source, /validateContentDocument\(JSON\.parse\(t\)\)/);
assert.match(source, /\[0-7\]\[0-9A-HJKMNP-TV-Z\]\{25\}/);
assert.match(source, /imageRefs 必须是数组/);
assert.match(source, /sha\}\)/);
assert.match(source, /r\.status===409\|\|r\.status===422/);
assert.match(source, /BASELINE_CONFLICT/);
assert.doesNotMatch(source, /myBlog-prod|localStorage|sessionStorage|console\.log/);
console.log('Review boundary source checks passed');
