'use strict';
const crypto=require('node:crypto');
const API='https://api.github.com', PROD='chance-hang/myBlog-prod', TEST='chance-hang/myBlog-test', CONTENT='content.json';
const sha=v=>crypto.createHash('sha256').update(v).digest('hex');const sort=v=>Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v;const canonical=v=>JSON.stringify(sort(v));
const die=m=>{throw Error(m)};
function validate(p){const {releaseId,planHash,...draft}=p;if(sha(canonical(draft))!==planHash||!releaseId.endsWith('-'+planHash.slice(0,8)))die('release plan hash rejected');if(p.repo!==PROD||!Array.isArray(p.selectedEntries)||!p.selectedEntries.length)die('release plan repository or selection rejected');if(!/^[a-f0-9]{40}$/.test(p.prodBaselineCommitSha)||!/^[a-f0-9]{40}$/.test(p.prodContentBlobSha))die('release plan baseline rejected');for(const i of p.images||[])if(!/^assets\/uploads\/[a-f0-9]{64}\.(png|jpe?g|gif|webp|svg)$/.test(i.path)||i.sha256!==i.path.match(/\/([a-f0-9]{64})\./)[1])die('release plan image rejected');return p}
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+process.env.PROD_PAT,'Content-Type':'application/json',...(opts.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)die('GitHub request failed '+r.status);return j}
async function publicApi(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json'}}),j=await r.json().catch(()=>({}));if(!r.ok)die('Test source request failed '+r.status);return j}
async function main(){const p=validate(JSON.parse(process.env.RELEASE_PLAN||''));if(!process.env.PROD_PAT)die('publisher secret unavailable');const ref=await api('/repos/'+PROD+'/git/ref/heads/main');if(ref.object.sha!==p.prodBaselineCommitSha)die('BASELINE_CONFLICT: Prod changed; no write attempted');const content=await api('/repos/'+PROD+'/git/blobs/'+p.prodContentBlobSha);const prod=JSON.parse(Buffer.from(content.content,'base64').toString());const sourceRef=await publicApi('/repos/'+TEST+'/git/commits/'+p.sourceTestCommitSha);const sourceTree=await publicApi('/repos/'+TEST+'/git/trees/'+sourceRef.tree.sha+'?recursive=1');const sourceContent=sourceTree.tree.find(x=>x.path===CONTENT);if(!sourceContent)die('Test content missing');const sourceBlob=await publicApi('/repos/'+TEST+'/git/blobs/'+sourceContent.sha);const test=JSON.parse(Buffer.from(sourceBlob.content,'base64').toString());const all=Object.entries({article:'articles',note:'notes',topic:'topics'}).flatMap(([k,list])=>test[list].map(v=>({k,v})));for(const s of p.selectedEntries){const x=all.find(a=>a.k===s.kind&&a.v.id===s.id);if(!x||sha(canonical(x.v))!==s.sourceHash)die('selected source mismatch');const list={article:'articles',note:'notes',topic:'topics'}[s.kind],i=prod[list].findIndex(v=>v.id===s.id);if(i<0)prod[list].push(x.v);else prod[list][i]=x.v}const tree=[{path:CONTENT,mode:'100644',type:'blob',content:JSON.stringify(prod,null,2)+'\n'}];for(const image of p.images||[]){const src=sourceTree.tree.find(x=>x.path===image.sourceRef);if(!src)die('image missing');const b=await publicApi('/repos/'+TEST+'/git/blobs/'+src.sha);const data=Buffer.from(b.content,'base64');if(sha(data)!==image.sha256)die('image hash conflict');const imageBlob=await makeBlob(data.toString('base64'),'base64');tree.push({path:image.path,mode:'100644',type:'blob',sha:imageBlob.sha})}const evidence={...p,publishedAtUtc:new Date().toISOString(),publisher:'github-actions'};tree.push({path:'docs/releases/'+p.releaseId+'.json',mode:'100644',type:'blob',content:JSON.stringify(evidence,null,2)+'\n'});const latest=await api('/repos/'+PROD+'/git/ref/heads/main');if(latest.object.sha!==p.prodBaselineCommitSha)die('BASELINE_CONFLICT: Prod changed before write; no write attempted');const base=await api('/repos/'+PROD+'/git/commits/'+latest.object.sha);const createdTree=await api('/repos/'+PROD+'/git/trees',{method:'POST',body:JSON.stringify({base_tree:base.tree.sha,tree})});const commit=await api('/repos/'+PROD+'/git/commits',{method:'POST',body:JSON.stringify({message:'admin: publish '+p.releaseId+' from Test '+p.sourceTestCommitSha+' baseline '+p.prodBaselineCommitSha,tree:createdTree.sha,parents:[latest.object.sha]})});await api('/repos/'+PROD+'/git/refs/heads/main',{method:'PATCH',body:JSON.stringify({sha:commit.sha,force:false})})}
main().catch(e=>{process.stderr.write(e.message+'\n');process.exit(1)});
